import Foundation
import SwiftData

/// SwiftData entity for mesh message queue.
/// Replaces Room MeshMessageEntity + MeshMessageDao.
/// Stores messages that need to be sent to server, either directly
/// via internet or relayed through the BLE mesh network.
@Model
final class MeshMessageEntity {
    var localId: Int? // Auto-generated by SwiftData
    @Attribute(.unique) var messageId: String
    var originDeviceMac: String
    var originDeviceFingerprint: String
    var hazardType: String
    var location: String
    var latitude: Double?
    var longitude: Double?
    var descriptionText: String
    var urgency: String
    var createdAtMillis: Int64
    var ttl: Int // Legacy column, kept for schema compat. No longer used for relay decisions.
    var hopCount: Int
    var status: String
    var transport: String
    var relayPath: String // Comma-separated device IDs
    var photoUrl: String?
    var contactInfo: String?
    var reporterUserId: Int?
    var serverReferenceId: String?
    var retryCount: Int
    var maxRetries: Int
    var lastAttemptAt: Date?
    var deliveredAt: Date?
    var createdAt: Date
    var expiresAt: Date
    var isOwnMessage: Bool
    var hasBeenRelayed: Bool
    
    init(
        messageId: String,
        originDeviceMac: String,
        originDeviceFingerprint: String,
        hazardType: String,
        location: String,
        latitude: Double? = nil,
        longitude: Double? = nil,
        descriptionText: String,
        urgency: String,
        createdAtMillis: Int64,
        ttl: Int = 0,
        hopCount: Int = 0,
        status: String = "pending",
        transport: String = "local_queue",
        relayPath: String = "",
        photoUrl: String? = nil,
        contactInfo: String? = nil,
        reporterUserId: Int? = nil,
        serverReferenceId: String? = nil,
        retryCount: Int = 0,
        maxRetries: Int = 5,
        lastAttemptAt: Date? = nil,
        deliveredAt: Date? = nil,
        createdAt: Date = Date(),
        expiresAt: Date = Date().addingTimeInterval(72 * 3600), // 72 hours
        isOwnMessage: Bool = true,
        hasBeenRelayed: Bool = false
    ) {
        self.messageId = messageId
        self.originDeviceMac = originDeviceMac
        self.originDeviceFingerprint = originDeviceFingerprint
        self.hazardType = hazardType
        self.location = location
        self.latitude = latitude
        self.longitude = longitude
        self.descriptionText = descriptionText
        self.urgency = urgency
        self.createdAtMillis = createdAtMillis
        self.ttl = ttl
        self.hopCount = hopCount
        self.status = status
        self.transport = transport
        self.relayPath = relayPath
        self.photoUrl = photoUrl
        self.contactInfo = contactInfo
        self.reporterUserId = reporterUserId
        self.serverReferenceId = serverReferenceId
        self.retryCount = retryCount
        self.maxRetries = maxRetries
        self.lastAttemptAt = lastAttemptAt
        self.deliveredAt = deliveredAt
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.isOwnMessage = isOwnMessage
        self.hasBeenRelayed = hasBeenRelayed
    }
    
    // MARK: - Domain Conversion
    
    func toDomain() -> MeshMessage {
        let pathList = relayPath.isEmpty ? [] : relayPath.split(separator: ",").map(String.init)
        return MeshMessage(
            messageId: messageId,
            originDeviceMac: originDeviceMac,
            originDeviceFingerprint: originDeviceFingerprint,
            hazardType: hazardType,
            location: location,
            latitude: latitude,
            longitude: longitude,
            description: descriptionText,
            urgency: urgency,
            createdAtMillis: createdAtMillis,
            hopCount: hopCount,
            status: MeshMessageStatus.fromValue(status),
            relayPath: pathList,
            photoUrl: photoUrl,
            contactInfo: contactInfo,
            reporterUserId: reporterUserId,
            serverReferenceId: serverReferenceId
        )
    }
    
    static func fromDomain(
        _ message: MeshMessage,
        isOwnMessage: Bool = true,
        transport: MeshTransport = .localQueue,
        overrideStatus: MeshMessageStatus? = nil
    ) -> MeshMessageEntity {
        MeshMessageEntity(
            messageId: message.messageId,
            originDeviceMac: message.originDeviceMac,
            originDeviceFingerprint: message.originDeviceFingerprint,
            hazardType: message.hazardType,
            location: message.location,
            latitude: message.latitude,
            longitude: message.longitude,
            descriptionText: message.description,
            urgency: message.urgency,
            createdAtMillis: message.createdAtMillis,
            hopCount: message.hopCount,
            status: (overrideStatus ?? message.status).value,
            transport: transport.value,
            relayPath: message.relayPath.joined(separator: ","),
            photoUrl: message.photoUrl,
            contactInfo: message.contactInfo,
            reporterUserId: message.reporterUserId,
            serverReferenceId: message.serverReferenceId,
            isOwnMessage: isOwnMessage
        )
    }
    
    // MARK: - Query Helpers (replaces DAO queries)
    
    /// Urgency sort weight for priority ordering
    var urgencyWeight: Int {
        switch urgency {
        case "critical": return 0
        case "high": return 1
        case "medium": return 2
        case "low": return 3
        default: return 4
        }
    }
    
    var isExpired: Bool {
        expiresAt <= Date()
    }
    
    var isPending: Bool {
        ["pending", "failed"].contains(status) && retryCount < maxRetries && !isExpired
    }
    
    var isRelayable: Bool {
        hasBeenRelayed && ["relayed", "pending", "sending"].contains(status)
    }
}
